development:
  adapter: sqlite
  database: db/development.db
  max_connections: 5
  pool_timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: wpxf
  max_connections: 5
  user: wpxf
  password: wpxf
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: sqlite
  database: db/test.db
  max_connections: 5
  pool_timeout: 5000
